### ISSUE TITLE
[Parent] Initial CLJ Server Config + Setup

### ISSUE THREAD

**Issue by bryanmikaelian** [nntp-clj/nntp-clj#1]
https://github.com/nntp-clj/nntp-clj/issues/1

The NNTP protocol is a application-layer protocol built on TCP. NNTP is used by Usenet servers and client to exchange.

The core IETF RFCS for this protcol are found at:

- [RFC3977](https://datatracker.ietf.org/doc/html/rfc3977)
- [RFC6048](https://datatracker.ietf.org/doc/html/rfc6048)

NNTP, being just a TCP protocol, will be implemented using Socket programming that is readily available in the JVM. This thin layer will be primarily responsible for:

- Opening and closing NNTP connections
- Receiving, validating, and responding to NNTP commands such as `INFO` or `ARTICLES`

[Netty](https://netty.io/) is one of the most popular framework to do socket programming on the JVM and we are going to leverage it to do our basic needs.

I think there are two approaches here, from a Clojure perspective:

1) We leverage https://github.com/clj-commons/aleph specifically the `aleph.tcp` namespace. The downside is this brings in the `manifold` library which may be overkill for us. The upside is it gives a TCP server practically for free that can listen on any port (NNTP traditionally listens on 119 for general use and 433 for bulk operations)
2) We re-implement our own TCP server, using Netty, with `aleph` being the inspiration. This approach may be rejected if `manifold` doesn't get in the way. However, if that ends up not being the case, the TCP implementation in aleph is roughly 200 lines of Clojure code calling various netty APIs. See https://github.com/clj-commons/aleph/blob/master/src/aleph/tcp.clj

On the more general side, we also need to get some of the foundational tooling pieces in place for this repo. The initial tools I'd like for us to leverage are:

- `deps` for dependency management
- `babashka` for tasks 
- https://github.com/juxt/aero for configuration
- https://github.com/weavejester/integrant for "systems" management
- `clojure.tools` for artifact building i.e. uberjars 
- Logging with with log4j and `clojure.tools.logging`
- Testing + Linting + CI with GitHub Actions

### Work Breakdown

- [x] Initial `src` directory and `core.clj`
- [x] Tooling
	- [x] `deps.edn`
	- [x] `babashka` + `clojure.tools` + tasks
	- [x] Logging
- [x] TCP server
	- [x] `aleph` or roll our own
- [x] System management
	- [x] Integrant managing the system
	- [x] Aero for configuring the system
- [x] CI with GitHub Actions
  - [x] Linter with clj-kondo
  - [x] Testing
